### ISSUE TITLE
Support for Elastic 2.0

### ISSUE THREAD

**Issue by phoenix-bjoern** [jprante/elasticsearch-analysis-decompound#17]
The readme.md references a link to a 2.0-rc download archive, but the link is broken.
Any thoughts on supporting recent ES version?

**Comment by mkraemer** [comment]
+1

**Comment by jprante** [comment]
Just released plugin version 2.1.0.0 for Elasticsearch 2.1.0

**Comment by mkraemer** [comment]
Awesome, thank you! :+1:
