### ISSUE TITLE
Support for ES 2.3.2

### ISSUE THREAD

**Issue by kateivamarmalade** [jprante/elasticsearch-analysis-decompound#31]
Now, it is not possible to install this plugin for ES 2.3.2. An error:
ERROR: Plugin [decompound] is incompatible with Elasticsearch [2.3.2]. Was designed for version [2.3.0]

Is it possible to have this plugin without new release for every minor elasticsearch release?

Thanks!

**Comment by gjozef** [comment]
needs just a version bump-up → https://github.com/jprante/elasticsearch-analysis-decompound/pull/32

**Comment by kateivamarmalade** [comment]
When can this pull request be accepted?

**Comment by jprante** [comment]
I have pushed plugin version 2.3.1.0, 2.3.2.0, and 2.3.3.0 for Elasticsearch 2.3.1, 2.3.2, 2.3.3 respectively.

**Comment by kateivamarmalade** [comment]
Thanks
