### ISSUE TITLE
xbib.com expired

### ISSUE THREAD

**Issue by Lavode** [jprante/elasticsearch-analysis-decompound#37]
Seems your website (xbib.com) expired, so downloads are not available anymore.
Probably a good occasion to also tackle #29 and set up an actual CI system. :)

**Comment by jprante** [comment]
You mean xbib.org. Sorry, it took the whole night to update Plesk, it restarted services. 

Now nginx is up again.

CI is already active. It is not of any help if your servers are transitioning from Centos 6.2 to 7.2

**Comment by Lavode** [comment]
Ah, perfect, thanks!
