### ISSUE TITLE
Elasticsearch 5.0 support

### ISSUE THREAD

**Issue by esidorov** [jprante/elasticsearch-analysis-decompound#43]
Hi, would it be possible to release an elasticsearch 5.0.x compatible version?

Thank you!

**Comment by bbguitar77** [comment]
👍

**Comment by marcuspoulton** [comment]
Version 5.x support would be most welcome!!

**Comment by jprante** [comment]
Version 5.1.1.0 has been released for Elasticsearch 5.1.1
