### ISSUE TITLE
Any chance to get a release for 5.4.3?

### ISSUE THREAD

**Issue by pschultz** [jprante/elasticsearch-analysis-decompound#50]
5.4.0 has a number of bugs that have been fixed in point releases. The release notes don't mention any changes to the Java API. Any chance you can put out a release for 5.4.3?

https://www.elastic.co/guide/en/elasticsearch/reference/current/release-notes-5.4.1.html
https://www.elastic.co/guide/en/elasticsearch/reference/current/release-notes-5.4.2.html
https://www.elastic.co/guide/en/elasticsearch/reference/current/release-notes-5.4.3.html

**Comment by jprante** [comment]
I just pushed out a 5.4.3.0 release for ES 5.4.3

**Comment by pschultz** [comment]
Thank you very much.
